INSERT INTO `productos` (`id_producto`, `id_vendedor`, `marca`, `categoria`, `tipo`, `nom_prod`, `sexo_prod`, `color`, `talla`, `entrega`, `descripcion`, `condicion`, `stock`, `precio`, `img_producto`) VALUES
(6, 1, 1, 1, 3, 'Zapatillas Jordan Retro', 'masculino', 'Blanco', 'M', 'persona', 'Zapatillas Jordan Retro en buen estado, poco uso.', 'bueno', 3, 10, 'jordan_retro.jpg'),
(7, 2, 2, 2, 7, 'Camiseta Lakers Kobe Bryant', 'femenino', 'Amarillo', 'S', 'domicilio', 'Camiseta oficial de los Lakers de Kobe Bryant, edición especial.', 'nuevo', 5, 20, 'lakers_kobe.jpg'),
(8, 3, 3, 3, 5, 'Balón Spalding NBA', 'femenino', 'Azul', 'L', 'tienda', 'Balón de baloncesto Spalding oficial NBA, perfecto para entrenar.', 'desgastado', 3, 30, 'spalding_nba.jpg'),
(9, 4, 4, 1, 6, 'Pantalones Nike Pro', 'masculino', 'Negro', 'XL', 'persona', 'Pantalones Nike Pro para entrenamientos intensos.', 'bueno', 1, 40, 'nike_pro.jpg'),
(10, 4, 4, 1, 8, 'Muñequeras Adidas', 'masculino', 'Negro', 'XL', 'persona', 'Muñequeras deportivas Adidas, absorben el sudor.', 'bueno', 1, 40, 'adidas_munequeras.jpg'),
(11, 4, 4, 1, 8, 'Rodilleras McDavid', 'masculino', 'Negro', 'XL', 'persona', 'Rodilleras McDavid para proteger las articulaciones.', 'bueno', 1, 40, 'mcdavid_rodilleras.jpg'),
(12, 4, 4, 1, 8, 'Calcetines Nike Elite', 'femenino', 'Negro', 'XL', 'persona', 'Calcetines Nike Elite con amortiguación especial.', 'bueno', 1, 40, 'nike_elite.jpg'),
(13, 4, 4, 1, 2, 'Sudadera Golden State Warriors', 'masculino', 'Azul', 'XL', 'persona', 'Sudadera oficial de los Warriors, edición 2022.', 'bueno', 1, 40, 'warriors_sudadera.jpg'),
(14, 4, 4, 1, 4, 'Gorra Chicago Bulls', 'masculino', 'Rojo', 'L', 'persona', 'Gorra original de los Chicago Bulls, ajustable.', 'bueno', 1, 40, 'bulls_gorra.jpg'),
(15, 4, 4, 1, 8, 'Riñonera Nike Sportswear', 'masculino', 'Negro', 'M', 'persona', 'Riñonera Nike ideal para llevar objetos pequeños.', 'bueno', 1, 40, 'nike_rinonera.jpg'),
(16, 4, 4, 1, 8, 'Mochila Under Armour', 'masculino', 'Gris', 'L', 'persona', 'Mochila Under Armour con compartimento para zapatillas.', 'bueno', 1, 40, 'underarmour_mochila.jpg'),
(17, 4, 4, 1, 8, 'Mallas deportivas Jordan', 'masculino', 'Negro', 'XL', 'persona', 'Mallas Jordan para mayor comodidad en la cancha.', 'bueno', 1, 40, 'jordan_mallas.jpg'),
(18, 4, 4, 1, 8, 'Gafas de protección Nike', 'masculino', 'Transparente', 'Única', 'persona', 'Gafas deportivas Nike para proteger los ojos.', 'bueno', 1, 40, 'nike_gafas.jpg'),
(19, 4, 4, 1, 8, 'Banda de resistencia Wilson', 'masculino', 'Rojo', 'Única', 'persona', 'Banda de resistencia Wilson para mejorar el salto.', 'bueno', 1, 40, 'wilson_resistencia.jpg'),
(20, 5, 5, 2, 5, 'Balón Molten Oficial FIBA', 'masculino', 'Naranja', 'M', 'tienda', 'Balón Molten oficial, usado en torneos FIBA.', 'nuevo', 1, 50, 'molten_fiba.jpg'),
(21, 6, 2, 3, 3, 'Zapatillas Adidas Harden Vol. 6', 'femenino', 'Blanco/Rojo', 'L', 'persona', 'Zapatillas de baloncesto Adidas Harden Vol. 6 en excelente estado.', 'bueno', 2, 75, 'harden_vol6.jpg'),
(22, 7, 3, 2, 7, 'Camiseta Boston Celtics Larry Bird', 'femenino', 'Verde', 'M', 'domicilio', 'Camiseta retro de los Boston Celtics, modelo Larry Bird.', 'nuevo', 4, 50, 'celtics_bird.jpg'),
(23, 8, 4, 1, 6, 'Pantalón corto Jordan Dri-FIT', 'masculino', 'Negro', 'XL', 'tienda', 'Pantalón corto Jordan Dri-FIT para entrenamientos.', 'bueno', 3, 35, 'jordan_drifit.jpg'),
(24, 9, 1, 4, 5, 'Balón Wilson Evolution', 'masculino', 'Naranja', 'Única', 'persona', 'Balón de baloncesto Wilson Evolution, gran agarre.', 'bueno', 5, 45, 'wilson_evolution.jpg'),
(25, 10, 2, 5, 8, 'Cinta para el pelo Nike', 'masculino', 'Negro', 'Única', 'persona', 'Cinta para el pelo Nike, ideal para absorber el sudor.', 'bueno', 6, 15, 'nike_cinta.jpg'),
(26, 6, 3, 1, 8, 'Medias compresivas Under Armour', 'femenino', 'Blanco', 'L', 'domicilio', 'Medias Under Armour para mejorar la circulación en juegos.', 'nuevo', 3, 20, 'underarmour_medias.jpg'),
(27, 7, 4, 3, 8, 'Protector bucal Shock Doctor', 'masculino', 'Transparente', 'Única', 'tienda', 'Protector bucal Shock Doctor para máxima protección.', 'bueno', 7, 25, 'shockdoctor_bucal.jpg'),
(28, 8, 5, 2, 7, 'Camiseta Chicago Bulls Jordan #23', 'masculino', 'Rojo/Negro', 'XL', 'persona', 'Camiseta de los Bulls con el icónico número 23 de Jordan.', 'bueno', 4, 60, 'bulls_jordan.jpg'),
(29, 9, 1, 1, 3, 'Zapatillas Nike LeBron 20', 'masculino', 'Azul', 'M', 'persona', 'Zapatillas Nike LeBron 20 con suela de gran amortiguación.', 'bueno', 2, 110, 'lebron_20.jpg'),
(30, 10, 2, 5, 8, 'Mochila Spalding Training', 'femenino', 'Negro', 'Única', 'persona', 'Mochila Spalding con compartimento especial para balones.', 'bueno', 3, 55, 'spalding_mochila.jpg'),
(31, 6, 3, 4, 8, 'Rodilleras Nike Pro', 'masculino', 'Negro', 'L', 'tienda', 'Rodilleras Nike Pro con máxima protección para impactos.', 'nuevo', 4, 30, 'nike_rodilleras.jpg'),
(32, 7, 4, 2, 4, 'Gorra NBA Finals Warriors', 'masculino', 'Azul/Dorado', 'Única', 'persona', 'Gorra oficial de las NBA Finals del equipo Warriors.', 'bueno', 2, 25, 'warriors_finals_gorra.jpg'),
(33, 8, 5, 3, 8, 'Muñequeras Jordan', 'masculino', 'Rojo', 'Única', 'domicilio', 'Muñequeras Jordan de alta absorción de sudor.', 'bueno', 6, 20, 'jordan_muñequeras.jpg'),
(34, 9, 1, 1, 7, 'Camiseta Dallas Mavericks Luka Doncic', 'masculino', 'Azul', 'M', 'persona', 'Camiseta oficial de Luka Doncic con los Mavericks.', 'nuevo', 5, 55, 'mavericks_luka.jpg'),
(35, 10, 2, 2, 2, 'Sudadera Los Angeles Lakers', 'masculino', 'Amarillo/Morado', 'XL', 'persona', 'Sudadera oficial de los Lakers, temporada 2023.', 'bueno', 3, 65, 'lakers_sudadera.jpg'),
(36, 6, 3, 1, 3, 'Zapatillas Puma Clyde Court', 'masculino', 'Naranja', 'L', 'persona', 'Zapatillas Puma Clyde Court, estilo retro-moderno.', 'bueno', 2, 85, 'puma_clyde.jpg'),
(37, 7, 4, 3, 6, 'Pantalón Nike Dri-FIT', 'masculino', 'Negro', 'L', 'tienda', 'Pantalón largo Nike Dri-FIT con tecnología de transpiración.', 'nuevo', 3, 40, 'nike_drifit_pantalon.jpg'),
(38, 8, 5, 2, 5, 'Balón Spalding Street Phantom', 'masculino', 'Negro/Rojo', 'Única', 'persona', 'Balón de baloncesto Spalding ideal para exteriores.', 'bueno', 5, 35, 'spalding_phantom.jpg'),
(39, 9, 1, 4, 3, 'Zapatillas Converse All Star Pro BB', 'masculino', 'Blanco/Azul', 'M', 'persona', 'Zapatillas Converse diseñadas para el baloncesto moderno.', 'bueno', 3, 90, 'converse_probb.jpg'),
(40, 10, 2, 5, 4, 'Gorra New Era Brooklyn Nets', 'masculino', 'Negro/Blanco', 'Única', 'persona', 'Gorra ajustable New Era de los Brooklyn Nets.', 'bueno', 4, 30, 'nets_gorra.jpg');